apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bbn3oatob-python 
  janus-idp.io/tekton: bbn3oatob-python
  backstage.io/kubernetes-id: bbn3oatob-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bbn3oatob-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml