apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bbn3oatob-python
  janus-idp.io/tekton: bbn3oatob-python
  backstage.io/kubernetes-id: bbn3oatob-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bbn3oatob-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
