apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bbn3oatob-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bbn3oatob-python 
  name: bbn3oatob-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bbn3oatob-python 
